// District label codes keyed by GeoJSON shapeName and common Romanian variants.
const DISTRICT_SHORT_CODES = {
  "Anenii Noi": "AN",
  "Balti": "Bălți",
  "Bălți": "Bălți",
  "Bălţi": "Bălți",
  "Basarabeasca": "BS",
  "Bender": "Bender",
  "Tighina": "Bender",
  "Briceni": "BR",
  "Cahul": "CH",
  "Calarasi": "CL",
  "Călărași": "CL",
  "Călăraşi": "CL",
  "Cantemir": "CT",
  "Causeni": "CS",
  "Căușeni": "CS",
  "Căuşeni": "CS",
  "Chisinau": "CHIȘINĂU",
  "Chișinău": "CHIȘINĂU",
  "Chişinău": "CHIȘINĂU",
  "Cimislia": "CM",
  "Cimișlia": "CM",
  "Cimişlia": "CM",
  "Criulei": "CR",
  "Criuleni": "CR",
  "Donduseni": "DN",
  "Dondușeni": "DN",
  "Donduşeni": "DN",
  "Drochia": "DR",
  "Dubasari": "DB",
  "Dubăsari": "DB",
  "Edinet": "ED",
  "Edineț": "ED",
  "Edineţ": "ED",
  "Falesti": "FL",
  "Fălești": "FL",
  "Făleşti": "FL",
  "Floresti": "FR",
  "Florești": "FR",
  "Floreşti": "FR",
  "Gagauzia": "UTAG",
  "Găgăuzia": "UTAG",
  "Unitatea Teritorială Autonomă Găgăuzia": "UTAG",
  "Comrat": "UTAG",
  "Glodeni": "GL",
  "Hincesti": "HN",
  "Hîncești": "HN",
  "Hînceşti": "HN",
  "Ialoveni": "IL",
  "Leova": "LV",
  "Nisporeni": "NS",
  "Ocnita": "OC",
  "Ocnița": "OC",
  "Ocniţa": "OC",
  "Orhei": "OR",
  "RIscani": "RS",
  "Rîșcani": "RS",
  "Rîşcani": "RS",
  "Rezina": "RZ",
  "SIngerei": "SG",
  "Sîngerei": "SG",
  "Soldanesti": "SD",
  "Șoldănești": "SD",
  "Şoldăneşti": "SD",
  "Soroca": "SR",
  "Stefan Voda": "SV",
  "Ștefan Vodă": "SV",
  "Ştefan Vodă": "SV",
  "Straseni": "ST",
  "Strășeni": "ST",
  "Străşeni": "ST",
  "Taraclia": "TR",
  "Telenesti": "TL",
  "Telenești": "TL",
  "Teleneşti": "TL",
  "Transnistria": "Transnistria",
  "Tiraspol": "Tiraspol",
  "Ungheni": "UN"
};

function districtLabel(name) {
  if (!name) return '???';
  return DISTRICT_SHORT_CODES[name] || name;
}
